services:
  - type: pserv
    name: petbloom-db
    plan: free
    
  - type: web
    name: petbloom-backend
    env: python
    plan: free
    buildCommand: "cd back-end && pip install -r requirements.txt && prisma generate && prisma db push"
    startCommand: "cd back-end && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petbloom-db
          property: connectionString
      - key: FBASE_CREDENTIALS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: FRONTEND_URL
        value: https://petbloom.netlify.app
